{
 "title": "SmartFridgeDONE",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Average Temperature Last Minute",
   "type": "stat",
   "description": "Red if below 0 °C, Green above.",
   "gridPos": { "h": 6, "w": 6, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  avg(temperature) AS \"temperature\"\nFROM temperature\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Average Ethylene Level Last Minute",
   "type": "stat",
   "description": "Green below 300, Red above",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  avg(ethylene_level) AS \"ethylene_level\"\nFROM ripening_notifier\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Average Oxygen Level Last Minutee",
   "type": "stat",
   "description": "Red if below 270 ppt, Green if above",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  avg(oxygen) AS \"oxygen\"\nFROM oxygen\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Temperature Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  temperature\nFROM temperature\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Ethylene Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  id\nFROM oxygen\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Oxygen Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  oxygen\nFROM oxygen\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Percentage Chiller ON Last 10 Minutes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 1, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,10m),\n  avg(chiller) AS \"chiller\"\nFROM temperature\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,10m)"
    }
   ]
  },
  {
   "title": "Percentage Oxygen Emitter ON Last 10 Minutes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,10m),\n  avg(emitter) AS \"emitter\"\nFROM oxygen\nWHERE\n  $__timeFilter(timestamp)\nGROUP BY 1\nORDER BY $__timeGroup(timestamp,10m)"
    }
   ]
  }
 ]
}